version: '3.8'

services:
  web:
    build: .
    command: sh -c "uv run python manage.py migrate && uv run gunicorn game_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - dev-db:/app/db
    ports:
      - "8081:8000"
    env_file:
      - .env

volumes:
  dev-db: